import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";
import Menu from "../components/Menu";
import NavBar from "../components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AceDesign | Practice Project",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen">
      {/* LEFT */}
      <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-4">
        <Link
        href="/"
        className="flex items-center justify-center lg:justify-start gap-2">
        <Image src="/icon.svg" alt="" height={30} width={30}/>
        <span className="hidden lg:block font-bold">AceDesign</span>
        </Link>
        <Menu />
      </div>
      {/* RIGHT */}
      <div className="bg-gray-100 w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] overflow-scroll flex flex-col">
        <NavBar />
        {children}
      </div>
    </div>
  );
}