// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Emma Carter",
    email: "emma.carter@example.co.uk",
    photo: "/avatars/teacher-1.svg",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "45 Park Lane, London, UK",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Lucas Müller",
    email: "lucas.mueller@example.de",
    photo: "/avatars/teacher-2.svg",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Hauptstraße 12, 10115 Berlin, Germany",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Sofia Rossi",
    email: "sofia.rossi@example.it",
    photo: "/avatars/teacher-3.svg",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Via Roma 10, 00184 Rome, Italy",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Liam O'Connor",
    email: "liam.oconnor@example.ie",
    photo: "/avatars/teacher-4.svg",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "23 O'Connell St, Dublin, Ireland",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Ava Williams",
    email: "ava.williams@example.ca",
    photo: "/avatars/teacher-5.svg",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "88 Queen St, Toronto, Canada",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Noah Smith",
    email: "noah.smith@example.au",
    photo: "/avatars/teacher-6.svg",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "12 Elm St, Sydney, Australia",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Isabella García",
    email: "isabella.garcia@example.es",
    photo: "/avatars/teacher-7.svg",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "Calle Mayor 5, 28013 Madrid, Spain",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Oliver Johansson",
    email: "oliver.johansson@example.se",
    photo: "/avatars/teacher-8.svg",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Storgatan 7, 111 22 Stockholm, Sweden",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Mia Dubois",
    email: "mia.dubois@example.fr",
    photo: "/avatars/teacher-9.svg",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "14 Rue de Rivoli, 75004 Paris, France",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Ethan Tanaka",
    email: "ethan.tanaka@example.jp",
    photo: "/avatars/teacher-10.svg",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "2-3-4 Shibuya, Tokyo, Japan",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Noah Bennett",
    email: "noah.bennett@example.co.uk",
    photo: "/avatars/student-1.svg",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "77 Baker St, London, UK",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Olivia Martínez",
    email: "olivia.martinez@example.es",
    photo: "/avatars/student-2.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle Alcalá 22, 28014 Madrid, Spain",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Liam Fischer",
    email: "liam.fischer@example.de",
    photo: "/avatars/student-3.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Lindenstraße 4, 10115 Berlin, Germany",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Emma Moreau",
    email: "emma.moreau@example.fr",
    photo: "/avatars/student-4.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "5 Rue du Château, 75008 Paris, France",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Sophia Romano",
    email: "sophia.romano@example.it",
    photo: "/avatars/student-5.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Piazza Navona 3, 00186 Rome, Italy",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Lucas Anderson",
    email: "lucas.anderson@example.ca",
    photo: "/avatars/student-6.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "101 King St, Toronto, Canada",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Ava Svensson",
    email: "ava.svensson@example.se",
    photo: "/avatars/student-7.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Drottninggatan 10, 111 51 Stockholm, Sweden",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Mateo Álvarez",
    email: "mateo.alvarez@example.ar",
    photo: "/avatars/student-8.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle Florida 100, Buenos Aires, Argentina",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Isabella Novák",
    email: "isabella.novak@example.cz",
    photo: "/avatars/student-9.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "nám. Svobody 1, 602 00 Brno, Czech Republic",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Ethan Kim",
    email: "ethan.kim@example.kr",
    photo: "/avatars/student-10.svg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "12 Gangnam-daero, Seoul, South Korea",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Oliver Bennett",
    students: ["Noah Bennett"],
    email: "oliver.bennett@example.co.uk",
    phone: "1234567890",
    address: "77 Baker St, London, UK",
  },
  {
    id: 2,
    name: "Carmen Martínez",
    students: ["Olivia Martínez"],
    email: "carmen.martinez@example.es",
    phone: "1234567890",
    address: "Calle Alcalá 22, 28014 Madrid, Spain",
  },
  {
    id: 3,
    name: "Klaus Fischer",
    students: ["Liam Fischer"],
    email: "klaus.fischer@example.de",
    phone: "1234567890",
    address: "Lindenstraße 4, 10115 Berlin, Germany",
  },
  {
    id: 4,
    name: "Claire Moreau",
    students: ["Emma Moreau"],
    email: "claire.moreau@example.fr",
    phone: "1234567890",
    address: "5 Rue du Château, 75008 Paris, France",
  },
  {
    id: 5,
    name: "Marco Romano",
    students: ["Sophia Romano"],
    email: "marco.romano@example.it",
    phone: "1234567890",
    address: "Piazza Navona 3, 00186 Rome, Italy",
  },
  {
    id: 6,
    name: "Sandra Anderson",
    students: ["Lucas Anderson"],
    email: "sandra.anderson@example.ca",
    phone: "1234567890",
    address: "101 King St, Toronto, Canada",
  },
  {
    id: 7,
    name: "Johan Svensson",
    students: ["Ava Svensson"],
    email: "johan.svensson@example.se",
    phone: "1234567890",
    address: "Drottninggatan 10, 111 51 Stockholm, Sweden",
  },
  {
    id: 8,
    name: "Lucía Álvarez",
    students: ["Mateo Álvarez"],
    email: "lucia.alvarez@example.ar",
    phone: "1234567890",
    address: "Calle Florida 100, Buenos Aires, Argentina",
  },
  {
    id: 9,
    name: "Petr Novák",
    students: ["Isabella Novák"],
    email: "petr.novak@example.cz",
    phone: "1234567890",
    address: "nám. Svobody 1, 602 00 Brno, Czech Republic",
  },
  {
    id: 10,
    name: "Min-Jae Kim",
    students: ["Ethan Kim"],
    email: "minjae.kim@example.kr",
    phone: "1234567890",
    address: "12 Gangnam-daero, Seoul, South Korea",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];